DROP DATABASE IF EXISTS iris;
CREATE DATABASE iris;
USE iris;

CREATE TABLE user
( uid			INT UNSIGNED  	PRIMARY KEY 	AUTO_INCREMENT
, username		VARCHAR(30)		NOT NULL
, email			VARCHAR(35)		NOT NULL
, password		VARCHAR(80)		NOT NULL
, first_name	VARCHAR(30)		NOT NULL
, last_name		VARCHAR(30)		NOT NULL
);

CREATE TABLE journal
( jid			INT UNSIGNED 	PRIMARY KEY 	AUTO_INCREMENT
, uid			INT UNSIGNED 	NOT NULL
, title			VARCHAR(100)	NOT NULL
, theme			VARCHAR(30)		NOT NULL
, FOREIGN KEY (uid) REFERENCES user(uid)
);

CREATE TABLE page
( pid			INT UNSIGNED 	PRIMARY KEY 	AUTO_INCREMENT
, jid			INT UNSIGNED 	NOT NULL
, uid			INT UNSIGNED 	NOT NULL
, title			VARCHAR(100)	NOT NULL
, event_date	DATE 			NOT NULL
, content		TEXT			NOT NULL
, page_number	INT UNSIGNED	NOT NULL
, FOREIGN KEY (jid) REFERENCES journal(jid)
, FOREIGN KEY (uid) REFERENCES user(uid)
);